import { ParsedSchematic } from './parseKicad';

interface SignalSnapshot {
  ch1?: { frequency: string; vpp: string; vmin: string; vmax: string };
  ch2?: { frequency: string; vpp: string; vmin: string; vmax: string };
  trigger: string;
  acquisition: string;
}

interface ExportOptions {
  timestamp: Date;
  scenario: string;
  mode: string;
  signal: SignalSnapshot;
  protocolLines: string[];
  schematic: ParsedSchematic | null;
  aiResponse: string;
}

export function buildMarkdownReport(opts: ExportOptions): string {
  const ts = opts.timestamp.toISOString().replace('T', ' ').slice(0, 19);
  const lines: string[] = [];

  lines.push(`# HWBench Debug Report`);
  lines.push(`**Timestamp:** ${ts}  `);
  lines.push(`**Scenario:** ${opts.scenario} · ${opts.mode} mode`);
  lines.push('');

  // Signal snapshot
  lines.push('## Signal Snapshot');
  lines.push('');
  lines.push('| Channel | Frequency | Vpp | Range |');
  lines.push('|---------|-----------|-----|-------|');
  if (opts.signal.ch1) {
    const c = opts.signal.ch1;
    lines.push(`| CH1 | ${c.frequency} | ${c.vpp} | ${c.vmin} → ${c.vmax} |`);
  }
  if (opts.signal.ch2) {
    const c = opts.signal.ch2;
    lines.push(`| CH2 | ${c.frequency} | ${c.vpp} | ${c.vmin} → ${c.vmax} |`);
  }
  lines.push('');
  lines.push(`Trigger: ${opts.signal.trigger}  `);
  lines.push(`Acquisition: ${opts.signal.acquisition}`);
  lines.push('');

  // Protocol traffic
  if (opts.protocolLines.length > 0) {
    lines.push('## Protocol Traffic');
    lines.push('');
    lines.push('```');
    opts.protocolLines.forEach(l => lines.push(l));
    lines.push('```');
    lines.push('');
  }

  // Schematic
  if (opts.schematic && opts.schematic.nets.length > 0) {
    const { fileName, nets, componentCount } = opts.schematic;
    lines.push(`## Schematic — ${fileName}`);
    lines.push(`${nets.length} nets · ${componentCount} components`);
    lines.push('');
    lines.push('| Net | Components |');
    lines.push('|-----|-----------|');
    for (const net of nets.slice(0, 30)) {
      const comps = net.entries.map(e => `${e.ref}(${e.value}).pin${e.pin}`).join(', ');
      lines.push(`| ${net.netName} | ${comps || '—'} |`);
    }
    if (nets.length > 30) lines.push(`| *(${nets.length - 30} more nets)* | |`);
    lines.push('');
  }

  // AI diagnosis
  lines.push('## AI Diagnosis');
  lines.push('');
  lines.push(opts.aiResponse.trim());
  lines.push('');
  lines.push('---');
  lines.push('*Generated by HWBench · hwbench-frontend.vercel.app*');

  return lines.join('\n');
}

export function downloadMarkdown(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
